INSERT INTO `jokes` (`category`,`joke`) VALUES ('KIDJOKES','Why did the chicken cross the road?\nTo get to the other side!');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('KIDJOKES','Dirty Joke: The boy fell into the mud.\nClean Joke: He took a shower!');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('DADJOKES','My wife is so negative. I remembered the car seat, the stroller, AND the diaper bag. Yet all she can talk about is how I forgot the baby.!');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('DADJOKES','Q. Why did the scarecrow win an award?\nA. Because he was outstanding in his field.');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('MOMJOKES','Don’t wake up mom! There are at least seven species who eat their young. Your mom may be one of them.');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('MOMJOKES','You know you’re a mom when…\n\n…picking up another human to smell their butt is not only normal but totally necessary');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('KNOCKKNOCK','Knock! Knock!\nWho’s there?\nSays.\nSays who?\nSays me, that’s who!');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('TECHNOLOGY','Q. How did the programmer die in the shower?\nA. He read the shampoo bottle instructions: Lather. Rinse. Repeat.');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('TECHNOLOGY','How many programmers does it take to change a light bulb?\nNone – It’s a hardware problem');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('TECHNOLOGY','Why do programmers always mix up Halloween and Christmas?\nBecause Oct 31 equals Dec 25.');
INSERT INTO `jokes` (`category`,`joke`) VALUES ('TECHNOLOGY','Knock, knock.\nWho’s there?\nvery long pause….\nJava.');